### PR TITLE
Adds usage message when push-zdd is ran without arguments

### PR DESCRIPTION
**Pull request by trayo**
We noticed when you try to run `cf push-zdd` there is no feedback from the command.

Now when you run the `push-zdd` command, it prints usage:

```
$ cf push-zdd
USAGE:
   Push a single app (with or without a manifest):
   cf push APP_NAME [-b BUILDPACK_NAME] [-c COMMAND] [-d DOMAIN] [-f MANIFEST_PATH]
   [-i NUM_INSTANCES] [-k DISK] [-m MEMORY] [-n HOST] [-p PATH] [-s STACK] [-t TIMEOUT]
   [--no-hostname] [--no-manifest] [--no-route] [--no-start]
```

cc: @jordanicollier

### CODE REVIEW

**Comment by trayo** [comment]
We aren't able to view the wercker link because they are marked as private.

I think we were confused about the way to run tests and were using 'go test'. We were getting duplicate test output because of 'suite_test.go' and 'autopilot_test.go' having it's own suite as well.

I think that might be the breaking change and will update the PR as an attempt to fix it.

**Comment by trayo** [comment]
We are getting this error when trying to run `./testrunner`:

```
--> Preparing step: wercker-init
--> Preparing step: setup-go-workspace
ERROR --> Step failed: setup environment
Get https://s3.amazonaws.com/wercker-production-steps/4e06faae-92dd-4a0b-9b5f-4e3ed9ad1a7d: x509: certificate signed by unknown authority
ERROR Get https://s3.amazonaws.com/wercker-production-steps/4e06faae-92dd-4a0b-9b5f-4e3ed9ad1a7d: x509: certificate signed by unknown authority
```

Could this have something to do with the private network we are on?

**Comment by xchapter7x** [comment]
changes are failing in wercker for this PR. Ill make the wercker app public so you can view the output.

we use wercker a lot. When run locally it will spin up docker containers and run everything in the exact same container as it will eventually run in the wercker service. So it is really consistent and reliable. executing ./testrunner is simply a convenience wrapper to running the wercker cli and testing the repo.

Also, in regards to the specific failures, those suits are required to run the tests, as we are using ginkgo and gomega which is a BDD testing framework. Also, we are using godeps to vendor up dependencies which would require you to run `godep go test ./...` rather than `go test ./...`

In regards to the error you pasted above, it looks like your network is man in the middle hijacking your certs. Reason i say this is b/c s3.amazonaws.com def has a valid cert, but the error says it doesnt.

once you get the build green I'd be happy to accept a pull request for a feature enhancement.

**Comment by trayo** [comment]
We are still working on this and running into dependency issues. We had to install [gvm](https://github.com/moovweb/gvm) to get our local go version on 1.4.2. 

We have our local `./testrunner` up to the same point that it is failing on wercker and will continue on it tomorrow.

**Comment by trayo** [comment]
@xchapter7x We got all the dependencies taken care of and got the build passing again.

We had a question though, are the `suite_test.go` and `rewind/suite_test.go` necessary? The suite test runners seem to also be duplicated in `autopilot_test.go` and `rewind/rewind_test.go`.

**Comment by trayo** [comment]
Also, are we supposed to push up a new binary?

**Comment by xchapter7x** [comment]
in regards to the suite_test.go files sprinkled around i should explain
what they do.

We use ginkgo and gomega to support a BDD syntax in our tests. There are 2
general ways to call your tests if you are using this framework rather than
the builtin golang test package directly.

1) you could call the tests via `ginkgo`command. Which would remove the
requirement to have these suite files everywhere. However, it would require
you call your tests using `ginkgo` and would inhibit your ability to just
call `go test ./...` as is standard testing practice in golang.

2) you could add these suite files, which wrap the ginkgo calls in a
standard golang test function. This allows you to call your tests however
you want. So both means of test running are supported. Drawback in this
case is requiring a bunch of suite files sprinkled around.

I generally opt for the 2nd option, so people have the option of calling it
however they want.

In regards to binaries, dont commit/push binaries. That should be the
output of the automated build process.
If there are binaries in there now, its either cruft from when i forked the
main autopilot, or a missed gitignore somewhere (which should be called out
and added).

-John

2015-10-30 10:34 GMT-04:00 Travis Yoder notifications@github.com:

**Comment by trayo** [comment]
The reason I ask about the `suite_test.go` is because the usual way I've used Ginkgo is to have an `autopilot_test.go` and an `autopilot_suite_test.go`. The `suite_test.go` is supposed to be responsible for [this line](https://github.com/xchapter7x/autopilot/blob/master/autopilot_test.go#L15) of code and currently it's in the `autopilot_test.go` **as well as** in the `suite_test.go` on [this line](https://github.com/xchapter7x/autopilot/blob/master/suite_test.go#L10) and causes duplicated output in your console:

image

Also, I think the binary is missing in the `gitingore`. Git is tracking one version and so when we makes changes it shows that the tracked version differs from our own. We figured that the binary should be built from the pipeline and didn't commit the differing one.

Thanks John!

**Comment by xchapter7x** [comment]
You are correct that is a popular naming convention.

I merely remove the prefix in my suite filenames. Thats just something i've
been doing lately b/c it seemed redundant. it is clearly the suite file for
the package it is in, so the package name being there as a prefix, as said,
seems like un-necessary duplication.

I would say, either should be fine, as long as the convention used is
consistent across the entire project.

-John

2015-10-30 11:01 GMT-04:00 Travis Yoder notifications@github.com:

**Comment by trayo** [comment]
I was trying to point out the duplication in the code, more specifically. There is an 'Autopilot Suite' in the `autopilot_test.go` _that runs the tests in_ `autopilot_test.go` and there is a `Suite` in the `suite_test.go` _that runs the tests in_ `autopilot_test.go`.

I'm trying to understand if there is a benefit to having two suite's running the same tests and having duplicated output.

**Comment by xchapter7x** [comment]
Oh, i see what you;re saying
https://github.com/xchapter7x/autopilot/blob/master/autopilot_test.go#L15
and
https://github.com/xchapter7x/autopilot/blob/master/suite_test.go#L10

Yes, good catch. This is indeed cruft from when I forked, and mistakenly
added a 2nd suite.

One of those should def be removed.

-John

2015-10-30 13:56 GMT-04:00 Travis Yoder notifications@github.com:

**Comment by JordanICollier** [comment]
Would like us to remove one of them in this PR?

**Comment by xchapter7x** [comment]
i will def accept a PR removing cruft..
feel free to shame me in the commit message as well :)

thanks

2015-10-30 14:53 GMT-04:00 Jordan I Collier notifications@github.com:

**Pull request merged**
